export {default as MainController} from './MainController'
export {default as Modal} from './Modal'
export {default as ItemList} from './ItemList'
export {default as SideMenu} from './SideMenu'
export {default as SliderButton} from './SliderButton'
export {default as Profile} from './Profile'
export {default as MovieInformation} from './MovieInformation'